### ISSUE TITLE
correct way to wait all motors to finish motion before taking a point in scan_nd?

### ISSUE THREAD

**Issue by imrealkaren** [NSLS-II/bluesky#489] opened 2016-06-13 17:59 UTC
What's the correct way to ensure motors finishing positions before taking a point in scan_nd?
Please see life table below:

```python
BlueSky [81]: x_motor = tomo_stage.finex_top

BlueSky [82]: z_motor = tomo_stage.finez_top

BlueSky [83]: xlist = numpy.linspace(xstart, xstop, hnumstep+1)

BlueSky [84]: zlist = numpy.linspace(zstart, zstop, hnumstep+1)

BlueSky [85]: xz_cycler = cycler(x_motor, xlist) + cycler(z_motor, zlist)

BlueSky [87]: plan = scan_nd([current_preamp], xz_cycler)

BlueSky [88]: plan = subs_wrapper(plan, [LiveTable([x_motor, z_motor, 'current_preamp_ch0'])])

BlueSky [89]: gs.RE(plan)
+-----------+------------+----------------------+------------------------------------+----------------------+------------------------------------+--------------------+
|   seq_num |       time | tomo_stage_finex_top | tomo_stage_finex_top_user_setpoint | tomo_stage_finez_top | tomo_stage_finez_top_user_setpoint | current_preamp_ch0 |
+-----------+------------+----------------------+------------------------------------+----------------------+------------------------------------+--------------------+
|         1 | 13:57:01.1 |          68.27200000 |                        11.71572875 |          11.72200000 |                        68.28427125 |        0.000000102 |
|         2 | 13:57:01.5 |          13.42100000 |                        25.85786438 |          68.28700000 |                        54.14213562 |        0.000000102 |
|         3 | 13:57:02.0 |          13.42100000 |                        40.00000000 |          46.17300000 |                        40.00000000 |        0.000000102 |
|         4 | 13:57:02.4 |          38.17800000 |                        54.14213562 |          46.17300000 |                        25.85786438 |        0.000000102 |
|         5 | 13:57:02.9 |          55.02900000 |                        68.28427125 |          25.85700000 |                        11.71572875 |        0.000000102 |
+-----------+------------+----------------------+------------------------------------+----------------------+------------------------------------+--------------------+
generator scan_nd ['219ffa'] (scan num: 353)
Out[89]: ['219ffa16-d7ac-48ca-938b-77d24e9b0616']

**Comment by tacaswell** [comment] 2016-06-13 18:07
Something is going very wrong there.   The underlying plan _should_ be waiting.  Can do

```python
gs.RE.msg_hook = print
```

This will produce alot of output, but will allow use to check if the wait messages are really there.

How are these motors implemented?

**Comment by tacaswell** [comment] 2016-06-13 18:09
https://github.com/NSLS-II-SRX/ipython_ophyd/blob/plan_hacking/profile_xf05id1/startup/05-endstation.py#L84 is definition of the Device.

**Comment by klauer** [comment] 2016-06-13 18:21
I'm relatively certain the scan and ophyd are acting as expected. The issue is very likely that the IOC for the PiezoJena isn't reporting its done status properly.

**Comment by imrealkaren** [comment] 2016-06-13 19:46
Here is the output:
```python
BlueSky [90]: gs.RE.msg_hook = print

BlueSky [91]: plan = scan_nd([current_preamp], xz_cycler)

BlueSky [92]: plan = subs_wrapper(plan, [LiveTable([x_motor, z_motor, 'current_preamp_ch0'])])

BlueSky [93]: gs.RE(plan)
subscribe: (None), ('all', <bluesky.callbacks.core.LiveTable object at 0x7fceb2cbe438>), {}
stage: (CurrentPreampZebra(prefix='XF:05IDA{IM:1}', name='current_preamp', read_attrs=['ch0', 'ch1', 'ch2', 'ch3', 'exp_time', 'initi_trigger', 'zebra_trigger', 'zebra_pulse_3_source'], configuration_attrs=[])), (), {}
stage: (SRXTomo(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:', name='tomo_stage', read_attrs=['y', 'theta', 'roll', 'pitch', 'finex_top', 'finey_top', 'finez_top'], configuration_attrs=[])), (), {}
open_run: (None), (), {'num_steps': 5, 'detectors': ['current_preamp'], 'plan_name': 'scan_nd', 'motors': ['tomo_stage_finex_top', 'tomo_stage_finez_top'], 'plan_args': {'cycler': "(cycler(EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:XFT}Mtr', name='tomo_stage_finex_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu']), [11.715728752538098, 25.857864376269049, 40.0, 54.142135623730951, 68.284271247461902]) + cycler(EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:ZFT}Mtr', name='tomo_stage_finez_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu']), [68.284271247461902, 54.142135623730951, 40.0, 25.857864376269049, 11.715728752538102]))", 'detectors': ["CurrentPreampZebra(prefix='XF:05IDA{IM:1}', name='current_preamp', read_attrs=['ch0', 'ch1', 'ch2', 'ch3', 'exp_time', 'initi_trigger', 'zebra_trigger', 'zebra_pulse_3_source'], configuration_attrs=[])"], 'per_step': 'None'}}
checkpoint: (None), (), {}
set: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:ZFT}Mtr', name='tomo_stage_finez_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (68.284271247461902,), {'group': 'set-6460a4'}
set: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:XFT}Mtr', name='tomo_stage_finex_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (11.715728752538098,), {'group': 'set-6460a4'}
wait: (None), (), {'group': 'set-6460a4'}
trigger: (CurrentPreampZebra(prefix='XF:05IDA{IM:1}', name='current_preamp', read_attrs=['ch0', 'ch1', 'ch2', 'ch3', 'exp_time', 'initi_trigger', 'zebra_trigger', 'zebra_pulse_3_source'], configuration_attrs=[])), (), {'group': 'trigger-6b4a2e'}
trigger: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:ZFT}Mtr', name='tomo_stage_finez_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (), {'group': 'trigger-6b4a2e'}
trigger: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:XFT}Mtr', name='tomo_stage_finex_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (), {'group': 'trigger-6b4a2e'}
wait: (None), (), {'group': 'trigger-6b4a2e'}
create: (None), (), {'name': 'primary'}
read: (CurrentPreampZebra(prefix='XF:05IDA{IM:1}', name='current_preamp', read_attrs=['ch0', 'ch1', 'ch2', 'ch3', 'exp_time', 'initi_trigger', 'zebra_trigger', 'zebra_pulse_3_source'], configuration_attrs=[])), (), {}
read: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:ZFT}Mtr', name='tomo_stage_finez_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (), {}
read: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:XFT}Mtr', name='tomo_stage_finex_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (), {}
save: (None), (), {}
+-----------+------------+----------------------+------------------------------------+----------------------+------------------------------------+--------------------+
|   seq_num |       time | tomo_stage_finex_top | tomo_stage_finex_top_user_setpoint | tomo_stage_finez_top | tomo_stage_finez_top_user_setpoint | current_preamp_ch0 |
+-----------+------------+----------------------+------------------------------------+----------------------+------------------------------------+--------------------+
|         1 | 15:42:49.4 |          68.27100000 |                        11.71572875 |          11.72200000 |                        68.28427125 |        0.000000102 |
checkpoint: (None), (), {}
set: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:ZFT}Mtr', name='tomo_stage_finez_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (54.142135623730951,), {'group': 'set-f014b8'}
set: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:XFT}Mtr', name='tomo_stage_finex_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (25.857864376269049,), {'group': 'set-f014b8'}
wait: (None), (), {'group': 'set-f014b8'}
trigger: (CurrentPreampZebra(prefix='XF:05IDA{IM:1}', name='current_preamp', read_attrs=['ch0', 'ch1', 'ch2', 'ch3', 'exp_time', 'initi_trigger', 'zebra_trigger', 'zebra_pulse_3_source'], configuration_attrs=[])), (), {'group': 'trigger-27fc36'}
trigger: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:ZFT}Mtr', name='tomo_stage_finez_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (), {'group': 'trigger-27fc36'}
trigger: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:XFT}Mtr', name='tomo_stage_finex_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (), {'group': 'trigger-27fc36'}
wait: (None), (), {'group': 'trigger-27fc36'}
create: (None), (), {'name': 'primary'}
read: (CurrentPreampZebra(prefix='XF:05IDA{IM:1}', name='current_preamp', read_attrs=['ch0', 'ch1', 'ch2', 'ch3', 'exp_time', 'initi_trigger', 'zebra_trigger', 'zebra_pulse_3_source'], configuration_attrs=[])), (), {}
read: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:ZFT}Mtr', name='tomo_stage_finez_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (), {}
read: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:XFT}Mtr', name='tomo_stage_finex_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (), {}
save: (None), (), {}
|         2 | 15:42:49.9 |          16.08300000 |                        25.85786438 |          68.28600000 |                        54.14213562 |        0.000000102 |
checkpoint: (None), (), {}
set: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:ZFT}Mtr', name='tomo_stage_finez_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (40.0,), {'group': 'set-e2b6d1'}
set: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:XFT}Mtr', name='tomo_stage_finex_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (40.0,), {'group': 'set-e2b6d1'}
wait: (None), (), {'group': 'set-e2b6d1'}
trigger: (CurrentPreampZebra(prefix='XF:05IDA{IM:1}', name='current_preamp', read_attrs=['ch0', 'ch1', 'ch2', 'ch3', 'exp_time', 'initi_trigger', 'zebra_trigger', 'zebra_pulse_3_source'], configuration_attrs=[])), (), {'group': 'trigger-f3b8a0'}
trigger: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:ZFT}Mtr', name='tomo_stage_finez_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (), {'group': 'trigger-f3b8a0'}
trigger: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:XFT}Mtr', name='tomo_stage_finex_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (), {'group': 'trigger-f3b8a0'}
wait: (None), (), {'group': 'trigger-f3b8a0'}
create: (None), (), {'name': 'primary'}
read: (CurrentPreampZebra(prefix='XF:05IDA{IM:1}', name='current_preamp', read_attrs=['ch0', 'ch1', 'ch2', 'ch3', 'exp_time', 'initi_trigger', 'zebra_trigger', 'zebra_pulse_3_source'], configuration_attrs=[])), (), {}
read: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:ZFT}Mtr', name='tomo_stage_finez_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (), {}
read: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:XFT}Mtr', name='tomo_stage_finex_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (), {}
save: (None), (), {}
|         3 | 15:42:50.3 |          16.08300000 |                        40.00000000 |          45.29200000 |                        40.00000000 |        0.000000102 |
checkpoint: (None), (), {}
set: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:ZFT}Mtr', name='tomo_stage_finez_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (25.857864376269049,), {'group': 'set-764c6f'}
set: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:XFT}Mtr', name='tomo_stage_finex_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (54.142135623730951,), {'group': 'set-764c6f'}
wait: (None), (), {'group': 'set-764c6f'}
trigger: (CurrentPreampZebra(prefix='XF:05IDA{IM:1}', name='current_preamp', read_attrs=['ch0', 'ch1', 'ch2', 'ch3', 'exp_time', 'initi_trigger', 'zebra_trigger', 'zebra_pulse_3_source'], configuration_attrs=[])), (), {'group': 'trigger-0ff153'}
trigger: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:ZFT}Mtr', name='tomo_stage_finez_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (), {'group': 'trigger-0ff153'}
trigger: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:XFT}Mtr', name='tomo_stage_finex_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (), {'group': 'trigger-0ff153'}
wait: (None), (), {'group': 'trigger-0ff153'}
create: (None), (), {'name': 'primary'}
read: (CurrentPreampZebra(prefix='XF:05IDA{IM:1}', name='current_preamp', read_attrs=['ch0', 'ch1', 'ch2', 'ch3', 'exp_time', 'initi_trigger', 'zebra_trigger', 'zebra_pulse_3_source'], configuration_attrs=[])), (), {}
read: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:ZFT}Mtr', name='tomo_stage_finez_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (), {}
read: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:XFT}Mtr', name='tomo_stage_finex_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (), {}
save: (None), (), {}
|         4 | 15:42:50.9 |          37.40200000 |                        54.14213562 |          45.29200000 |                        25.85786438 |        0.000000102 |
checkpoint: (None), (), {}
set: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:ZFT}Mtr', name='tomo_stage_finez_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (11.715728752538102,), {'group': 'set-fc1267'}
set: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:XFT}Mtr', name='tomo_stage_finex_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (68.284271247461902,), {'group': 'set-fc1267'}
wait: (None), (), {'group': 'set-fc1267'}
trigger: (CurrentPreampZebra(prefix='XF:05IDA{IM:1}', name='current_preamp', read_attrs=['ch0', 'ch1', 'ch2', 'ch3', 'exp_time', 'initi_trigger', 'zebra_trigger', 'zebra_pulse_3_source'], configuration_attrs=[])), (), {'group': 'trigger-aa8198'}
trigger: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:ZFT}Mtr', name='tomo_stage_finez_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (), {'group': 'trigger-aa8198'}
trigger: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:XFT}Mtr', name='tomo_stage_finex_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (), {'group': 'trigger-aa8198'}
wait: (None), (), {'group': 'trigger-aa8198'}
create: (None), (), {'name': 'primary'}
read: (CurrentPreampZebra(prefix='XF:05IDA{IM:1}', name='current_preamp', read_attrs=['ch0', 'ch1', 'ch2', 'ch3', 'exp_time', 'initi_trigger', 'zebra_trigger', 'zebra_pulse_3_source'], configuration_attrs=[])), (), {}
read: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:ZFT}Mtr', name='tomo_stage_finez_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (), {}
read: (EpicsMotor(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:XFT}Mtr', name='tomo_stage_finex_top', parent='tomo_stage', settle_time=0.0, timeout=None, read_attrs=['user_readback', 'user_setpoint'], configuration_attrs=['motor_egu'])), (), {}
save: (None), (), {}
|         5 | 15:42:51.4 |          54.13600000 |                        68.28427125 |          25.85800000 |                        11.71572875 |        0.000000101 |
close_run: (None), (), {}
+-----------+------------+----------------------+------------------------------------+----------------------+------------------------------------+--------------------+
generator scan_nd ['940cc0'] (scan num: 354)
unstage: (SRXTomo(prefix='XF:05IDD-ES:1{Stg:Tomo-Ax:', name='tomo_stage', read_attrs=['y', 'theta', 'roll', 'pitch', 'finex_top', 'finey_top', 'finez_top'], configuration_attrs=[])), (), {}
unstage: (CurrentPreampZebra(prefix='XF:05IDA{IM:1}', name='current_preamp', read_attrs=['ch0', 'ch1', 'ch2', 'ch3', 'exp_time', 'initi_trigger', 'zebra_trigger', 'zebra_pulse_3_source'], configuration_attrs=[])), (), {}
unsubscribe: (None), (), {'token': 8}
Out[93]: ['940cc0e2-72c6-40bf-8543-54cdb1f1d0de']

**Comment by tacaswell** [comment] 2016-06-20 00:33
Closing as the underlying issue is the IOCs are not correctly reporting when they are done moving, this is the proper usage of bluesky.

**Closed by tacaswell** 2016-06-20 00:33 UTC
