### ISSUE TITLE
[CSX] Another set() call in progress

### ISSUE THREAD

**Issue by cmazzoli** [NSLS-II/bluesky#1102] opened 2018-10-26 13:37 UTC
Since a while we get more and more of these errors.
Is this due to a communication delay/problem when trying to set the fccd exposure after a dark?
The same plan (one_long()) was successfully executed already 3 time in a raw before generating the following problem..

````
Gain bit set to 2 for a gain value of x1

Transient Scan ID: 110850     Time: 2018/10/26 01:57:19
Persistent Unique Scan ID: '0a9a4ce2-7dcc-4945-bec7-dfc77f048620'
New stream: 'baseline'
New stream: 'primary'                                                                                                                                                                                
+-----------+------------+-------------------+-------------------+-------------------+-------------------+
|   seq_num |       time | fccd_stats1_total | fccd_stats2_total | fccd_stats3_total | fccd_stats4_total |
+-----------+------------+-------------------+-------------------+-------------------+-------------------+
|         1 | 01:58:47.4 |         -79923382 |         -80033559 |        -651008475 |       -5246340033 |
+-----------+------------+-------------------+-------------------+-------------------+-------------------+
generator count ['0a9a4ce2'] (scan num: 110850)

Returning to intial conditions (pre-count).
        Total images per trigger are NOW:        300                                                                                                                                                 
	FCCD FCRIC gain value is NOW:		 auto


---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/Beamline/Commissioning/2018_10/20181025_evening.py in <module>()
----> 1 RE(night_plan())

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    668                     # it (unless it is a canceled error)
    669                     if exc is not None:
--> 670                         raise exc
    671 
    672             if self._interrupted:

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/run_engine.py in _run(self)
   1118             self.log.error("Run aborted")
   1119             self.log.error("%r", err)
-> 1120             raise err
   1121         finally:
   1122             # Some done_callbacks may still be alive in other threads.

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/run_engine.py in _run(self)
    996                         try:
    997                             msg = self._plan_stack[-1].throw(
--> 998                                 self._exception)
    999                         except Exception as e:
   1000                             # The current plan did not handle it,

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in __call__(self, plan)
   1236         plan = monitor_during_wrapper(plan, self.monitors)
   1237         plan = baseline_wrapper(plan, self.baseline)
-> 1238         return (yield from plan)

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in baseline_wrapper(plan, devices, name)
   1092         return (yield from plan)
   1093     else:
-> 1094         return (yield from plan_mutator(plan, insert_baseline))
   1095 
   1096 

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     73             # if we have a stashed exception, pass it along
     74             try:
---> 75                 msg = plan_stack[-1].throw(exception)
     76             except Exception as e:
     77                 # if we catch an exception,

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    722     plan1 = plan_mutator(plan, insert_after_open)
    723     plan2 = plan_mutator(plan1, insert_before_close)
--> 724     return (yield from plan2)
    725 
    726 

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     73             # if we have a stashed exception, pass it along
     74             try:
---> 75                 msg = plan_stack[-1].throw(exception)
     76             except Exception as e:
     77                 # if we catch an exception,

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     73             # if we have a stashed exception, pass it along
     74             try:
---> 75                 msg = plan_stack[-1].throw(exception)
     76             except Exception as e:
     77                 # if we catch an exception,

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in fly_during_wrapper(plan, flyers)
    780     plan1 = plan_mutator(plan, insert_after_open)
    781     plan2 = plan_mutator(plan1, insert_before_close)
--> 782     return (yield from plan2)
    783 
    784 

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     73             # if we have a stashed exception, pass it along
     74             try:
---> 75                 msg = plan_stack[-1].throw(exception)
     76             except Exception as e:
     77                 # if we catch an exception,

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     73             # if we have a stashed exception, pass it along
     74             try:
---> 75                 msg = plan_stack[-1].throw(exception)
     76             except Exception as e:
     77                 # if we catch an exception,

~/Beamline/Commissioning/2018_10/20181025_evening.py in night_plan()
     12     # snaking test
     13     yield from one_long(snaking=1)
---> 14     yield from one_long()
     15     # Escan test
     16     yield from EfixQ(dets,706.5,705,1,Eshift=0.0)

~/Beamline/Commissioning/2018_10/20181025_evening.py in one_long(snaking)
     28 
     29 def one_long(snaking = 0): #2h
---> 30     yield from mv(fccd.exposure,(.2,0,5))
     31     olog('Ptycho #{} at sample position (x:{:.4f}, y:{:.4f}), {:.2f} K, {:.3f} eV'.format((db[-1].get('start').get('scan_id'))+1,sx.user_readback.value,sy.readback.value,stemp.temp.B.T.value,pgm.energy.readback.value))
     32     yield from relative_outer_product_scan(dets,nanop.bz,-0.01,0.01,41,nanop.bx,-0.01,0.01,41,snaking)

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/plan_stubs.py in mv(*args)
    240     step, = utils.merge_cycler(cyl)
    241     for obj, val in step.items():
--> 242         ret = yield Msg('set', obj, val, group=group)
    243         status_objects.append(ret)
    244     yield Msg('wait', None, group=group)

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    161         try:
    162             # yield out the 'current message' and collect the return
--> 163             inner_ret = yield msg
    164         except GeneratorExit:
    165             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    161         try:
    162             # yield out the 'current message' and collect the return
--> 163             inner_ret = yield msg
    164         except GeneratorExit:
    165             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    161         try:
    162             # yield out the 'current message' and collect the return
--> 163             inner_ret = yield msg
    164         except GeneratorExit:
    165             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    161         try:
    162             # yield out the 'current message' and collect the return
--> 163             inner_ret = yield msg
    164         except GeneratorExit:
    165             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    161         try:
    162             # yield out the 'current message' and collect the return
--> 163             inner_ret = yield msg
    164         except GeneratorExit:
    165             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/run_engine.py in _run(self)
   1068                         # exceptions (coming in via throw) can be
   1069                         # raised
-> 1070                         response = yield from coro(msg)
   1071                     # special case `CancelledError` and let the outer
   1072                     # exception block deal with it.

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/asyncio/coroutines.py in coro(*args, **kw)
    208         @functools.wraps(func)
    209         def coro(*args, **kw):
--> 210             res = func(*args, **kw)
    211             if (base_futures.isfuture(res) or inspect.isgenerator(res) or
    212                 isinstance(res, CoroWrapper)):

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/run_engine.py in _set(self, msg)
   1822         group = kwargs.pop('group', None)
   1823         self._movable_objs_touched.add(msg.obj)
-> 1824         ret = msg.obj.set(*msg.args, **kwargs)
   1825         p_event = asyncio.Event(loop=self.loop)
   1826         pardon_failures = self._pardon_failures

/epics/xf/23id/ipython/profile_collection/startup/csx1/devices/areadetector.py in set(self, exp)
    195             self.parent.dg1.D.set(dd)
    196             self.parent.dg1.E.set(ee)
--> 197             self.parent.dg1.F.set(ff)
    198             self.parent.dg1.G.set(gg)
    199             self.parent.dg1.H.set(hh)

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/ophyd/signal.py in set(self, value, timeout, settle_time)
    928         '''
    929         if not self._put_complete:
--> 930             return super().set(value, timeout=timeout, settle_time=settle_time)
    931 
    932         # using put completion:

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/ophyd/signal.py in set(self, value, timeout, settle_time)
    179 
    180         if self._set_thread is not None:
--> 181             raise RuntimeError('Another set() call is still in progress')
    182 
    183         st = Status(self)

RuntimeError: Another set() call is still in progress


````

**Comment by cmazzoli** [comment] 2018-10-26 19:36
If I remember it correctly, once this errors hits, we are unable to get back in control of the device. Up to now the restart of BS is the only solution I know.
Two questions:
- Does this reply to your point?
- Do you have an alternative way of getting out of the impasse, other than restarting BS I mean?
Please let me know. Thanks.

**Comment by cmazzoli** [comment] 2018-11-02 18:34
It's Wen at CSX beamline now.
The issue Claudio reported above became urgent problem for CSX right now. We can only set FastCCD exposure for one time and error shows immediately for the second time. See below. For this, we cannot do any user operation. 
Can someone please have a look? 
````
Versions of DAMA software:

    - Bluesky    : v1.1.0
    - Ophyd      : v1.0.0
    - Databroker : v0.9.4

Links to Bluesky and Databroker tutorials:

    - http://nsls-ii.github.io/bluesky/tutorial.html
    - http://nsls-ii.github.io/databroker/tutorial.html

If you get lost or confused, then we want to know! We have a friendly chat channel:

    https://gitter.im/NSLS-II/DAMA

or you can file a bug to let us know where our documentation could be made more clear:

    https://github.com/NSLS-II/Bug-Reports/issues

bsui is running these commands now to start an interactive computing environment for data acquisition:
    $ conda activate collection-2018-1.0.1
    $ ipython --profile=collection 

Activating auto-logging. Current session state plus future input saved.
Filename       : /epics/xf/23id/ophyd/logs/xf23id1_log.py
Mode           : append
Output logging : False
Raw input log  : False
Timestamping   : False
State          : active
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

IPython profile: collection
Using matplotlib backend: Qt5Agg
Loading metadata history from /home/xf23id1/.config/bluesky/bluesky_history.db
/epics/xf/23id/ipython/profile_collection/startup/csx1/startup/__init__.py:4: PyGIWarning: Hkl was imported without specifying a version first. Use gi.require_version('Hkl', '5.0') before import to ensure that the right version gets loaded.
  from .endstation import *
/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/suspenders.py:505: UserWarning: bluesky.suspenders.SuspendOutBand is deprecated.
  warn("bluesky.suspenders.SuspendOutBand is deprecated.")
/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/ophyd/device.py:738: UserWarning: 'signal_names' has been renamed 'component_names' for clarity because it may include a mixture of Signals and Devices -- any Components. This alias may be removed in a future release of ophyd.
  warnings.warn("'signal_names' has been renamed 'component_names' for "

In [1]: %run -i startup.py

In [2]: RE(mv(fccd.exposure,(0.1, 0, 1)));

In [3]: RE(mv(fccd.exposure,(0.1, 0, 1)));
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/Beamline/Commissioning/2018_11/startup.py in <module>()
----> 1 RE(mv(fccd.exposure,(0.1, 0, 1)));

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    668                     # it (unless it is a canceled error)
    669                     if exc is not None:
--> 670                         raise exc
    671 
    672             if self._interrupted:

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/run_engine.py in _run(self)
   1118             self.log.error("Run aborted")
   1119             self.log.error("%r", err)
-> 1120             raise err
   1121         finally:
   1122             # Some done_callbacks may still be alive in other threads.

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/run_engine.py in _run(self)
    996                         try:
    997                             msg = self._plan_stack[-1].throw(
--> 998                                 self._exception)
    999                         except Exception as e:
   1000                             # The current plan did not handle it,

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in __call__(self, plan)
   1236         plan = monitor_during_wrapper(plan, self.monitors)
   1237         plan = baseline_wrapper(plan, self.baseline)
-> 1238         return (yield from plan)

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in baseline_wrapper(plan, devices, name)
   1092         return (yield from plan)
   1093     else:
-> 1094         return (yield from plan_mutator(plan, insert_baseline))
   1095 
   1096 

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     73             # if we have a stashed exception, pass it along
     74             try:
---> 75                 msg = plan_stack[-1].throw(exception)
     76             except Exception as e:
     77                 # if we catch an exception,

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    722     plan1 = plan_mutator(plan, insert_after_open)
    723     plan2 = plan_mutator(plan1, insert_before_close)
--> 724     return (yield from plan2)
    725 
    726 

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     73             # if we have a stashed exception, pass it along
     74             try:
---> 75                 msg = plan_stack[-1].throw(exception)
     76             except Exception as e:
     77                 # if we catch an exception,

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     73             # if we have a stashed exception, pass it along
     74             try:
---> 75                 msg = plan_stack[-1].throw(exception)
     76             except Exception as e:
     77                 # if we catch an exception,

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in fly_during_wrapper(plan, flyers)
    780     plan1 = plan_mutator(plan, insert_after_open)
    781     plan2 = plan_mutator(plan1, insert_before_close)
--> 782     return (yield from plan2)
    783 
    784 

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     73             # if we have a stashed exception, pass it along
     74             try:
---> 75                 msg = plan_stack[-1].throw(exception)
     76             except Exception as e:
     77                 # if we catch an exception,

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     73             # if we have a stashed exception, pass it along
     74             try:
---> 75                 msg = plan_stack[-1].throw(exception)
     76             except Exception as e:
     77                 # if we catch an exception,

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/plan_stubs.py in mv(*args)
    240     step, = utils.merge_cycler(cyl)
    241     for obj, val in step.items():
--> 242         ret = yield Msg('set', obj, val, group=group)
    243         status_objects.append(ret)
    244     yield Msg('wait', None, group=group)

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    161         try:
    162             # yield out the 'current message' and collect the return
--> 163             inner_ret = yield msg
    164         except GeneratorExit:
    165             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    161         try:
    162             # yield out the 'current message' and collect the return
--> 163             inner_ret = yield msg
    164         except GeneratorExit:
    165             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    161         try:
    162             # yield out the 'current message' and collect the return
--> 163             inner_ret = yield msg
    164         except GeneratorExit:
    165             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    161         try:
    162             # yield out the 'current message' and collect the return
--> 163             inner_ret = yield msg
    164         except GeneratorExit:
    165             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    161         try:
    162             # yield out the 'current message' and collect the return
--> 163             inner_ret = yield msg
    164         except GeneratorExit:
    165             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/run_engine.py in _run(self)
   1068                         # exceptions (coming in via throw) can be
   1069                         # raised
-> 1070                         response = yield from coro(msg)
   1071                     # special case `CancelledError` and let the outer
   1072                     # exception block deal with it.

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/asyncio/coroutines.py in coro(*args, **kw)
    208         @functools.wraps(func)
    209         def coro(*args, **kw):
--> 210             res = func(*args, **kw)
    211             if (base_futures.isfuture(res) or inspect.isgenerator(res) or
    212                 isinstance(res, CoroWrapper)):

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/run_engine.py in _set(self, msg)
   1822         group = kwargs.pop('group', None)
   1823         self._movable_objs_touched.add(msg.obj)
-> 1824         ret = msg.obj.set(*msg.args, **kwargs)
   1825         p_event = asyncio.Event(loop=self.loop)
   1826         pardon_failures = self._pardon_failures

/epics/xf/23id/ipython/profile_collection/startup/csx1/devices/areadetector.py in set(self, exp)
    202 
    203             # Set AreaDetector
--> 204             self.parent.cam.acquire_time.set(Efccd)
    205 
    206         # Now do period

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/ophyd/signal.py in set(self, value, timeout, settle_time)
    928         '''
    929         if not self._put_complete:
--> 930             return super().set(value, timeout=timeout, settle_time=settle_time)
    931 
    932         # using put completion:

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/ophyd/signal.py in set(self, value, timeout, settle_time)
    179 
    180         if self._set_thread is not None:
--> 181             raise RuntimeError('Another set() call is still in progress')
    182 
    183         st = Status(self)

RuntimeError: Another set() call is still in progress

In [4]: 


````

**Comment by tacaswell** [comment] 2018-11-02 20:20
What has changed in your profile or the IOC in the last week or so?

**Comment by tacaswell** [comment] 2018-11-02 20:54
Which underlying signal is getting stuck?

**Comment by tacaswell** [comment] 2018-11-02 21:05
Try using this plan istead

```python

def set_exposure(fccd, exp):
    # Exposure time = 0
    # Cycle time = 1
    Tc = 0.004
    To = 0.0035
    readout = 0.080
    
    if exp[0] is not None:
        Efccd = exp[0] + Tc + To
        # To = start of FastCCD Exposure
        aa = 0                          # Shutter open
        bb = Efccd - Tc + aa      # Shutter close
        cc = To * 3               # diag6 gate start
        dd = exp[0] - (Tc * 2)    # diag6 gate stop
        ee = 0                          # Channel Adv Start
        ff = 0.001                      # Channel Adv Stop
        gg = To                   # MCS Count Gate Start
        hh = exp[0] + To          # MCS Count Gate Stop

        # Set delay generator
        yield from bp.mv(fccd.dg1.A, aa)
        yield from bp.mv(fccd.dg1.B, bb)
        yield from bp.mv(fccd.dg1.C, cc)
        yield from bp.mv(fccd.dg1.D, dd)
        yield from bp.mv(fccd.dg1.E, ee)
        yield from bp.mv(fccd.dg1.F, ff)
        yield from bp.mv(fccd.dg1.G, gg)
        yield from bp.mv(fccd.dg1.H, hh)
        yield from bp.mv(fccd.dg2.A, 0)
        yield from bp.mv(fccd.dg2.B, 0.0005)

        # Set AreaDetector
        yield from bp.mv(fccd.cam.acquire_time, Efccd)

    # Now do period
    if exp[1] is not None:
        if exp[1] < (Efccd + self._readout):
            p = Efccd + self._readout
        else:
            p = exp[1]

    yield from bp.mv(fccd.cam.acquire_period, p)

    if exp[2] is not None:
        yield from bp.mv(fccd.cam.num_images, exp[2])

```

The issue is that in your custom set ( https://github.com/NSLS-II-CSX/xf23id1_profiles/blob/8fe44bcd546f8021bf9f5eca2a55954b39bf3de8/profile_collection/startup/csx1/devices/areadetector.py#L175-L218 ) you are calling `set` on all of the signal, but not actually waiting for them to finish.  Given that I have been told restarting the IOC fixed the problem, I suspect something went sideways on the IOC and this exception was an indication that you were not actually setting the camera the way you thought you were.

I think `and` ing all of the status objects you generate in that `set` together and returning that would also work, but I think shifting to plan is easier to debug / test.

**Comment by tacaswell** [comment] 2018-11-02 21:21
This is not bluesky bug, it is either in the beamline IOC or in the beamline profile, closing.

**Closed by tacaswell** 2018-11-02 21:21 UTC

**Comment by ambarb** [comment] 2020-12-22 16:55
It is important to note that this error goes away when running the detector slow enough.  SO if the acquire period is < 0.3s, then we run the risk of this error occurring .  It doesn't always occur if the acquire pries is <0.3s.
