### ISSUE TITLE
issue to retrive events/data from Xspress3

### ISSUE THREAD

**Issue by imrealkaren** [NSLS-II/bluesky#485] opened 2016-06-09 17:18 UTC
```python
BlueSky [12]: gs.RE(hf2dxrf(xstart=6.669,xstepsize=0.005,xnumstep=1,ystart=1.171,ystepsize=.005,ynumstep=1,acqtime=.3,numrois=1, i0map_show=False, itmap_show=False))
xstop = 6.6739999999999995
ystop = 1.176
+-----------+------------+------------+--------------------------+------------+--------------------------+--------------------+--------------------+------------------------------+
|   seq_num |       time | hf_stage_x | hf_stage_x_user_setpoint | hf_stage_y | hf_stage_y_user_setpoint | current_preamp_ch0 | current_preamp_ch2 | xs_channel1_rois_roi01_value |
+-----------+------------+------------+--------------------------+------------+--------------------------+--------------------+--------------------+------------------------------+
|         1 | 13:16:47.7 |   6.669000 |                 6.669000 |   1.170990 |                 1.171000 |        0.000000001 |        0.000000120 |                       0.0000 |
|         2 | 13:16:48.6 |   6.674000 |                 6.674000 |   1.171010 |                 1.171000 |        0.000000001 |        0.000000120 |                       0.0000 |
|         3 | 13:16:52.0 |   6.674000 |                 6.674000 |   1.175910 |                 1.176000 |        0.000000001 |        0.000000120 |                       0.0000 |
|         4 | 13:16:52.9 |   6.669000 |                 6.669000 |   1.175995 |                 1.176000 |        0.000000001 |        0.000000120 |                       0.0000 |
+-----------+------------+------------+--------------------------+------------+--------------------------+--------------------+--------------------+------------------------------+
generator outer_product_scan ['46b1de'] (scan num: 263)
Out[12]: ['46b1de99-e0a4-4d48-8957-46e067a1de6f']

BlueSky [13]: evs = list(get_events(db[-1], fill=True))
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-13-95d5428c472d> in <module>()
----> 1 evs = list(get_events(db[-1], fill=True))

/home/xf05id1/conda_envs/collection/lib/python3.4/site-packages/databroker/broker.py in get_events(self, headers, fields, name, fill, handler_registry, handler_overrides, **kwargs)
    316                          handler_overrides=handler_overrides,
    317                          plugins=self.plugins, **kwargs)
--> 318         for event in res:
    319             yield event
    320 

/home/xf05id1/conda_envs/collection/lib/python3.4/site-packages/databroker/core.py in get_events(mds, fs, headers, fields, name, fill, handler_registry, handler_overrides, plugins, **kwargs)
    197                     continue
    198                 if fill:
--> 199                     fill_event(fs, event, handler_registry, handler_overrides)
    200                 yield event
    201         # Now yield any events from plugins.

/home/xf05id1/conda_envs/collection/lib/python3.4/site-packages/databroker/core.py in fill_event(fs, event, handler_registry, handler_overrides)
     51             if data_key not in handler_overrides:
     52                 with fs.handler_context(handler_registry) as _fs:
---> 53                     event.data[data_key] = _fs.get_datum(value)
     54             else:
     55                 mock_registry = mock_registries[data_key]

/home/xf05id1/conda_envs/collection/lib/python3.4/site-packages/filestore/fs.py in retrieve(self, eid)
    143         return self._api.retrieve(self._datum_col, eid,
    144                                   self._datum_cache, self.get_spec_handler,
--> 145                                   logger)
    146 
    147     # back compat

/home/xf05id1/conda_envs/collection/lib/python3.4/site-packages/filestore/core.py in retrieve(col, eid, datum_cache, get_spec_handler, logger)
     57                         "datum cache can hold.")
     58 
---> 59     handler = get_spec_handler(datum['resource'])
     60     return handler(**datum['datum_kwargs'])
     61 

/home/xf05id1/conda_envs/collection/lib/python3.4/site-packages/filestore/fs.py in get_spec_handler(self, resource)
    262 
    263         spec = resource['spec']
--> 264         handler = self.handler_reg[spec]
    265         if self.version == 0:
    266             key = (str(resource['_id']), handler.__name__)

/home/xf05id1/conda_envs/collection/lib/python3.4/collections/__init__.py in __getitem__(self, key)
    803             except KeyError:
    804                 pass
--> 805         return self.__missing__(key)            # support subclasses that define __missing__
    806 
    807     def get(self, key, default=None):

/home/xf05id1/conda_envs/collection/lib/python3.4/collections/__init__.py in __missing__(self, key)
    795 
    796     def __missing__(self, key):
--> 797         raise KeyError(key)
    798 
    799     def __getitem__(self, key):

KeyError: 'XSP3'

BlueSky [14]:

**Comment by klauer** [comment] 2016-06-09 17:23
That means your xspress3 filestore handler isn't loaded. Try

```python
from hxntools.handlers import register
register()
```

**Comment by heroux** [comment] 2016-06-09 18:09
Is there a srxtools.handlers or you just have to know to use hxntools.handlers?


+++++++++++++++++++++++++++
Energy Sciences Directorate/Photon Science Division, Bldg 745 L107
Brookhaven National Laboratory
Upton, NY 11973, USA
Phone office:  631 344 4454

________________________________

**Comment by imrealkaren** [comment] 2016-06-09 20:50
Thanks Ken. I added that two lines into the 80-areadetectors.py in our configuration file.
It worked sometimes; but other times it would give errors:

case1: try to access data after the xrf/xanes scan completed; if I launch the same command again - evs = list(get_events(db[-1], fill=True))- it sometimes works but other times would show the same error.

```python
BlueSky [5]: evs = list(get_events(db[-1], fill=True))
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-5-95d5428c472d> in <module>()
----> 1 evs = list(get_events(db[-1], fill=True))

/home/xf05id1/conda_envs/collection/lib/python3.4/site-packages/databroker/broker.py in get_events(self, headers, fields, name, fill, handler_registry, handler_overrides, **kwargs)
    316                          handler_overrides=handler_overrides,
    317                          plugins=self.plugins, **kwargs)
--> 318         for event in res:
    319             yield event
    320 

/home/xf05id1/conda_envs/collection/lib/python3.4/site-packages/databroker/core.py in get_events(mds, fs, headers, fields, name, fill, handler_registry, handler_overrides, plugins, **kwargs)
    197                     continue
    198                 if fill:
--> 199                     fill_event(fs, event, handler_registry, handler_overrides)
    200                 yield event
    201         # Now yield any events from plugins.

/home/xf05id1/conda_envs/collection/lib/python3.4/site-packages/databroker/core.py in fill_event(fs, event, handler_registry, handler_overrides)
     51             if data_key not in handler_overrides:
     52                 with fs.handler_context(handler_registry) as _fs:
---> 53                     event.data[data_key] = _fs.get_datum(value)
     54             else:
     55                 mock_registry = mock_registries[data_key]

/home/xf05id1/conda_envs/collection/lib/python3.4/site-packages/filestore/fs.py in retrieve(self, eid)
    143         return self._api.retrieve(self._datum_col, eid,
    144                                   self._datum_cache, self.get_spec_handler,
--> 145                                   logger)
    146 
    147     # back compat

/home/xf05id1/conda_envs/collection/lib/python3.4/site-packages/filestore/core.py in retrieve(col, eid, datum_cache, get_spec_handler, logger)
     57                         "datum cache can hold.")
     58 
---> 59     handler = get_spec_handler(datum['resource'])
     60     return handler(**datum['datum_kwargs'])
     61 

/home/xf05id1/conda_envs/collection/lib/python3.4/site-packages/filestore/fs.py in get_spec_handler(self, resource)
    278         if root:
    279             rpath = os.path.join(root, rpath)
--> 280         ret = handler(rpath, **kwargs)
    281         h_cache[key] = ret
    282         return ret

/home/xf05id1/Repos/hxntools/hxntools/handlers/xspress3.py in __init__(self, filename, key)
     28         self._dataset = None
     29 
---> 30         self.open()
     31 
     32     def open(self):

/home/xf05id1/Repos/hxntools/hxntools/handlers/xspress3.py in open(self)
     34             return
     35 
---> 36         self._file = h5py.File(self._filename, 'r')
     37 
     38     def close(self):

/home/xf05id1/conda_envs/collection/lib/python3.4/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    270 
    271                 fapl = make_fapl(driver, libver, **kwds)
--> 272                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    273 
    274                 if swmr_support:

/home/xf05id1/conda_envs/collection/lib/python3.4/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
     90         if swmr and swmr_support:
     91             flags |= h5f.ACC_SWMR_READ
---> 92         fid = h5f.open(name, flags, fapl=fapl)
     93     elif mode == 'r+':
     94         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/tmp/edill/ramdisk/mc/conda-bld/work/h5py/_objects.c:2582)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/tmp/edill/ramdisk/mc/conda-bld/work/h5py/_objects.c:2541)()

h5py/h5f.pyx in h5py.h5f.open (/tmp/edill/ramdisk/mc/conda-bld/work/h5py/h5f.c:1824)()

case II. errors in closing hdf5 file during the scan:
```python
BlueSky [25]: xanes(erange = [8979-5, 8979+5], 
            estep = [1],  
            harmonic = None,            
            acqtime=0.2, i0scale = 1e8, itscale = 1e8,samplename='Cufoil',filename='Cu_dcmval_xrfmode')
+-----------+------------+---------------+--------------------+--------------------+------------------------------+
|   seq_num |       time | energy_energy | current_preamp_ch0 | current_preamp_ch2 | xs_channel1_rois_roi01_value |
+-----------+------------+---------------+--------------------+--------------------+------------------------------+
|         1 | 16:40:52.4 |         8.974 |        0.000001718 |        0.000000119 |                   19460.6361 |
|         2 | 16:40:54.2 |         8.975 |        0.000001718 |        0.000000119 |                   19929.6285 |
|         3 | 16:40:56.1 |         8.976 |        0.000001716 |        0.000000119 |                   20571.8435 |
|         4 | 16:40:57.9 |         8.977 |        0.000001701 |        0.000000119 |                   21772.5177 |
|         5 | 16:41:00.0 |         8.978 |        0.000001671 |        0.000000120 |                   23800.4718 |
|         6 | 16:41:01.7 |         8.979 |        0.000001619 |        0.000000119 |                   27205.6396 |
|         7 | 16:41:03.2 |         8.980 |        0.000001513 |        0.000000121 |                   32125.0195 |
|         8 | 16:41:04.6 |         8.981 |        0.000001348 |        0.000000119 |                   36814.7286 |
|         9 | 16:41:06.3 |         8.982 |        0.000001168 |        0.000000119 |                   42767.4736 |
|        10 | 16:41:07.4 |         8.983 |        0.000000871 |        0.000000119 |                   46472.4643 |
Failed to close file
Traceback (most recent call last):
  File "/home/xf05id1/Repos/hxntools/hxntools/handlers/xspress3.py", line 62, in __del__
    self.close()
  File "/home/xf05id1/Repos/hxntools/hxntools/handlers/xspress3.py", line 40, in close
    self._file.close()
AttributeError: 'NoneType' object has no attribute 'close'
Failed to close file
Traceback (most recent call last):
  File "/home/xf05id1/Repos/hxntools/hxntools/handlers/xspress3.py", line 62, in __del__
    self.close()
  File "/home/xf05id1/Repos/hxntools/hxntools/handlers/xspress3.py", line 40, in close
    self._file.close()
AttributeError: 'NoneType' object has no attribute 'close'
|        11 | 16:41:09.2 |         8.984 |        0.000000871 |        0.000000119 |                   48208.9304 |
+-----------+------------+---------------+--------------------+--------------------+------------------------------+
ListScan list_scan ['fa9bb3'] (scan num: 285)
<class 'list'>
['fa9bb393-e438-4240-874d-1a1c1fe38389']
fa9bb393-e438-4240-874d-1a1c1fe38389
6.668995000000001
1.1760000000000002

**Comment by tacaswell** [comment] 2016-06-09 20:55
I think the top traceback is missing some lines.

**Comment by tacaswell** [comment] 2016-06-09 20:57
Also, you have a funny file set up where the IOC writes to one drive and then it is mirrored to a second (which is what is eventually mounted under the path saved in filestore).  My guess is if you are trying this right after a scan has finished the file has not finished being copied over.

**Comment by klauer** [comment] 2016-06-09 20:57
@heroux it's a detector which was initially HXN-only and is now being used by other beamlines. Eventually, we'll move its support up into ophyd/filestore itself.

**Comment by klauer** [comment] 2016-06-09 20:59
@tacaswell That does seem like it would be a real problem for this sort of immediate post-scan callback...

**Comment by tacaswell** [comment] 2016-06-09 21:03
attn @gjwillms

**Comment by danielballan** [comment] 2016-06-09 21:05
@klauer I've been think it might be useful to have a pattern (a CallbackBase variant?) that fills events from filestore, patiently hammering filestore until the data is available. Without any better confirmation coming from the detectors, I don't think there's a better way.

**Comment by klauer** [comment] 2016-06-09 21:10
@imrealkaren I've pushed a fix for your case II to hxntools. Case (I) isn't clear just yet what is happening.

@danielballan sounds like a good idea. In this case, without SWMR and having a wonky file-copying mechanism from the IOC machine, reading from them wouldn't work until well after the scan finishes. Polling, as you say, is really the only logical and reliable method.

**Comment by cowanml** [comment] 2016-06-10 02:52
On Thu, 9 Jun 2016, K Lauer wrote:
...
> @danielballan sounds like a good idea. In this case, without SWMR and having
> a wonky file-copying mechanism from the IOC machine, reading from them
> wouldn't work until well after the scan finishes. Polling, as you say, is
> really the only logical and reliable method.


You could do something fancy with inotify to trigger the callback;
although unless the file appears all at once, not created and written
to, could have issues with partial files?

You could enhance or redo the file-copying mechanism to trigger the
callback on successful copy.

Or any chance of just eliminating the wonky file-copying?! :)

**Comment by gjwillms** [comment] 2016-06-10 11:29
It will be a hard sell to get rid of the copy step.  It is, imo, bad practice to store data in the same place that is currently being used for collection because it will lead to non-local users hammering the data collection machines during operations.  This is largely undesirable.

In this case, the copying is done by lsyncd and, in the future, the storage filesystem will not be NFS mounted by the analysis machines, but rather connected by fiber.

There's a good chance that something with ionotify would work.  Partial files will transiently exist, but I'd be surprised if they get parsed by the analysis software faster than they written to disk.  H5-like (or other indexed datafiles) library badness notwithstanding.

**Comment by cowanml** [comment] 2016-06-10 14:30
On Fri, 10 Jun 2016, gjwillms wrote:
> It will be a hard sell to get rid of the copy step. It is, imo, bad
> practice to store data in the same place that is currently being
> used for collection because it will lead to non-local users
> hammering the data collection machines during operations. This is
> largely undesirable.

I've had better luck going simple, having dedicated storage systems
(not direct attached storage on data collection systems), and making
sure they're up to snuff.


> In this case, the copying is done by lsyncd and, in the future, the storage filesystem will
> not be NFS mounted by the analysis machines, but rather connected by fiber.

Connected by fiber = gpfs?  I think with gpfs an inotify monitor would
need to be on the gpfs client writing the files, and with nfs it could
either be on the client writing the files or the nfs server.  It's
perfectly possible, but would require writing a little network
client/server on top of inotify to get the events back to the data
collection system.  Ceph and Lustre might support inotify across
clients, but that's not worth adding another cfs to our support
burden.


"Lsyncd ... aggregates and combines events for a few seconds and then
spawns one (or more) process(es) to synchronize the changes."

"Lsyncd is designed to synchronize a local directory tree with low
profile of expected changes to a remote mirror."

"DRBD operates on block device level. This makes it useful for
synchronizing systems that are under heavy load."

https://github.com/axkibe/lsyncd

Doesn't sound like lsyncd is intended for high bandwidth or rapid live sync and
you'll always have several seconds delay?  sleep(5) :)


> There's a good chance that something with ionotify would
> work. Partial files will transiently exist, but I'd be surprised if
> they get parsed by the analysis software faster than they written to
> disk. H5-like (or other indexed datafiles) library badness
> notwithstanding.

I'm having deja vu, I remember writing something to monitor for new
files, and check their size repeatedly until it stabilized.  I think
it was when x25 at nsls first got it's Dectris Pilatus 6M and it was
setup to synch files out to long term storage.  Fought with that for
sometime, ended up solving it by mounting and writing directly to high
performance storage from the detector computer.

**Comment by gjwillms** [comment] 2016-06-10 15:29
I'm using lsyncd as it was intended to be used.  Rapid or online feedback, imo, should not rely on stored data.  It's neither surprising nor alarming to me that all data is not immediately available via bluesky.  What is important to me is that we capture such occurrences and raise intelligible exceptions. 

We're all colored by our past and mine is guided by my experiences at APS and LCLS.  I will fight to keep data collection systems independent from user accessible storage systems because I have seen what can happen when things go wrong.

**Comment by tacaswell** [comment] 2016-06-20 00:34
Closing as the actionable issue (not registering the handlers) is solved.

**Closed by tacaswell** 2016-06-20 00:34 UTC
