### ISSUE TITLE
reverse search and cancel issue

### ISSUE THREAD

**Issue by ambarb** [NSLS-II/bluesky#309] opened 2016-01-30 19:21 UTC
Reverse search and cancel (^C) does not clean up properly.  Somehow the command is held in memory and the search result is still executed (it is not displayed on the next line). Two examples are below.  In the second, multiple ^Cs after the initial canel still results in search result execution. In followed by multiple ^C to create new lines does not clean up properly. In this last example, access at the beamline was removed from EPU2 (as it is the other branch's EPU) which is what is responsible for all the errors.  

```python
n [23]: 

In [23]: 

In [23]: mov(pgm_en,459.50)

   pgm_en             

    459.447305        


(reverse-i-search)`ep': wh_pos(epu2)
KeyboardInterrupt

In [24]: wh_pos(epu2)

+------------+----------+-----------+------------+
| Positioner |    Value | Low Limit | High Limit |
+------------+----------+-----------+------------+
| epu2_phase |  0.00023 | -24.60000 |   24.60000 |
| epu2_gap   | 21.96699 |  12.00000 |  239.00000 |
+------------+----------+-----------+------------+

(reverse-i-search)`epu1': ascan(epu1.gap,80.8,81.6,30)
KeyboardInterrupt

In [25]: 
KeyboardInterrupt

In [25]: 
KeyboardInterrupt

In [25]: 
KeyboardInterrupt

In [25]: 
KeyboardInterrupt

In [25]: ascan(epu1.gap,80.8,81.6,30)
Transient Scan ID: 56899
Persistent Unique Scan ID: '056bd6d5-b6e6-4df8-b079-602dd7000539'
+------------+--------------+---------------------+---------------------+------------------------+----------------+
|   seq_num  |        time  |  epu1_gap_readback  |  epu1_gap_setpoint  |  epu1_gap_stop_signal  |      sclr_ch2  |
+------------+--------------+---------------------+---------------------+------------------------+----------------+
Run aborted
 put returned 'Write access denied'
/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
+------------+--------------+---------------------+---------------------+------------------------+----------------+
/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/bluesky/run_engine.py:1180: UserWarning: A ValueError('attempt to get argmax of an empty sequence',) was raised during the processing of a stop Document. The error will be ingored to avoid interrupting data collection. To investigate, set RunEngine.ignore_callback_exceptions = False and run again.
  "and run again." % (exc, name.name))
---------------------------------------------------------------------------
CASeverityException                       Traceback (most recent call last)
<ipython-input-25-11629fed1a54> in <module>()
----> 1 ascan(epu1.gap,80.8,81.6,30)

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/bluesky/simple_scans.py in __call__(self, motor, start, finish, intervals, time, subs, **kwargs)
    254         original_times = _set_acquire_time(time)
    255         result = super().__call__(motor, start, finish, intervals + 1,
--> 256                                   subs=subs, **kwargs)
    257         _unset_acquire_time(original_times)
    258         return result

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/bluesky/simple_scans.py in __call__(self, subs, sub_factories, *args, **kwargs)
    150         # Any remainging kwargs go the RE. To be safe, no args are passed
    151         # to RE; RE args effectively become keyword-only arguments.
--> 152         return gs.RE(self.scan, _subs, **kwargs)
    153 
    154 

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/bluesky/run_engine.py in __call__(self, plan, subs, **metadata_kw)
    529                 exc = self._task.exception()
    530                 if exc is not None:
--> 531                     raise exc
    532 
    533         return self._run_start_uids

/home/xf23id1/conda_envs/collection/lib/python3.4/asyncio/tasks.py in _step(***failed resolving arguments***)
    237                 # We use the `send` method directly, because coroutines
    238                 # don't have `__iter__` and `__next__` methods.
--> 239                 result = coro.send(None)
    240             else:
    241                 result = coro.throw(exc)

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/bluesky/run_engine.py in _run(self)
    700             logger.error("Run aborted")
    701             logger.error("%s", err)
--> 702             raise err
    703         finally:
    704             self.state = 'idle'

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/bluesky/run_engine.py in _run(self)
    673                         raise
    674                     except Exception as e:
--> 675                         self._genstack[-1].throw(e)
    676                     self.debug('RE.state: ' + self.state)
    677                     self.debug('msg: {}\n  response: {}'.format(msg, response))

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/bluesky/plans.py in __iter__(self)
     75             yield Msg('kickoff', flyer, block_group='_flyers')
     76             yield Msg('wait', None, '_flyers')
---> 77         yield from self._gen()
     78         for flyer in self.flyers:
     79             yield Msg('collect', flyer, block_group='_flyers')

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/bluesky/plans.py in _gen(self)
    187         for step in self._abs_steps:
    188             yield Msg('checkpoint')
--> 189             yield Msg('set', self.motor, step, block_group='A')
    190             yield Msg('wait', None, 'A')
    191             yield Msg('create')

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/bluesky/run_engine.py in _run(self)
    669                         self.debug("About to process: {0}, {1}".
    670                                    format(coro, msg))
--> 671                         response = yield from coro(msg)
    672                     except KeyboardInterrupt:
    673                         raise

/home/xf23id1/conda_envs/collection/lib/python3.4/asyncio/coroutines.py in coro(*args, **kw)
    204         @functools.wraps(func)
    205         def coro(*args, **kw):
--> 206             res = func(*args, **kw)
    207             if isinstance(res, futures.Future) or inspect.isgenerator(res):
    208                 res = yield from res

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/bluesky/run_engine.py in _set(self, msg)
   1003         block_group = msg.kwargs.pop('block_group', None)
   1004         self._movable_objs_touched.add(msg.obj)
-> 1005         ret = msg.obj.set(*msg.args, **msg.kwargs)
   1006         if block_group:
   1007             p_event = asyncio.Event()

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/ophyd/positioner.py in set(self, new_position, wait, moved_cb, timeout)
    189         """
    190         return self.move(new_position, wait=wait, moved_cb=moved_cb,
--> 191                          timeout=timeout)
    192 
    193     def _repr_info(self):

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/ophyd/pv_positioner.py in move(self, position, wait, **kwargs)
    176                 ret = super().move(position, wait=False, **kwargs)
    177                 self._started_moving = False
--> 178                 self._move_async(position, **kwargs)
    179                 return ret
    180         except KeyboardInterrupt:

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/ophyd/pv_positioner.py in _move_async(self, position, **kwargs)
    295         else:
    296             self.setpoint.put(position, wait=False,
--> 297                               callback=done_moving)

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/ophyd/signal.py in put(self, value, force, **kwargs)
    531 
    532         self._write_pv.put(value, use_complete=use_complete,
--> 533                            **kwargs)
    534 
    535         old_value = self._setpoint

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/epics/pv.py in put(self, value, wait, timeout, use_complete, callback, callback_data)
    337                       wait=wait, timeout=timeout,
    338                       callback=callback,
--> 339                       callback_data=callback_data)
    340 
    341     def __putCallbackStub(self, pvname=None, **kws):

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/epics/ca.py in wrapper(*args, **kwds)
    403                                                         name(chid), timeout))
    404 
--> 405         return fcn(*args, **kwds)
    406     wrapper.__doc__ = fcn.__doc__
    407     wrapper.__name__ = fcn.__name__

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/epics/ca.py in put(chid, value, wait, timeout, callback, callback_data)
   1353     ret = libca.ca_array_put_callback(ftype, count, chid,
   1354                                       data, _CB_PUTWAIT, 0)
-> 1355     PySEVCHK('put', ret)
   1356     poll(evt=1.e-4, iot=0.05)
   1357     if wait:

/home/xf23id1/conda_envs/collection/lib/python3.4/site-packages/epics/ca.py in PySEVCHK(func_name, status, expected)
    432     if status == expected:
    433         return status
--> 434     raise CASeverityException(func_name, message(status))
    435 
    436 def withSEVCHK(fcn):

CASeverityException:  put returned 'Write access denied'

```

**Comment by ambarb** [comment] 2016-01-30 20:44
Another example.  This time some other command was executed after initial ^C from reverse search.  


```


(reverse-i-search)`mov': movr(eta,1)
KeyboardInterrupt

In [29]: grabit
Select area of screen to grab .........


```

**Comment by tacaswell** [comment] 2016-01-30 20:53
I can reproduce the issue with 'reverse-i-search' (started via ctrl-r ) in a clean `IPython` session (with out any of our site specific code imported), I will see if I can chase this upstream at all.

The second case (with the write access denied) what behavior do you expect?

**Comment by tacaswell** [comment] 2016-01-30 21:15
Seems that this is a long-standing upstream bug: https://github.com/ipython/ipython/issues/1286

**Comment by tacaswell** [comment] 2016-01-30 21:17
and it looks like hitting `ctrl-g` will correctly clean up.

**Comment by danielballan** [comment] 2016-01-30 21:25
Another work-around: you don't need to use Ctrl+R to reverse-search in IPython. Unlike in a standard bash shell, you can use the up arrow at any point (say, after typing a few characters) to reverse-search at any point. I gather IPython supports Ctrl+R for compatibility with people's habits carrying over from bash, but as I can tell you can just avoid it altogether without losing any reverse-search functionality.

**Comment by tacaswell** [comment] 2016-01-30 21:31
the IPython type + up search only works on the start of a line, ctrl-r searches anywhere in the line so you do lose quite a bit of power by not using the readline search.

**Comment by ambarb** [comment] 2016-01-30 23:40
I found escape also cleans up okay. Cntl-c to escape cntrol-r is done in spec because one automatically gets a newline. It saves time instead of having to backspace after an escape exit.  I guess you have to weigh your options against a potential disaster at the beamline and new users that use spec everywhere else.

**Comment by danielballan** [comment] 2016-01-31 15:37
I'm closing this issue. Follow the IPython issue linked above (ipython/ipython#1286) instead.

**Comment by tacaswell** [comment] 2016-01-31 16:58
We need a local work around for this.

**Comment by tacaswell** [comment] 2016-02-01 04:10
The upstream fix is https://bugs.python.org/issue24266

**Comment by danielballan** [comment] 2016-09-15 17:43
Upcoming rollout (Python 3.5, IPython 5.x) will remove readline from the equation. Closing.

**Closed by danielballan** 2016-09-15 17:43 UTC
