### ISSUE TITLE
Suspender investigation test on CSX

### ISSUE THREAD

**Issue by stuartcampbell** [NSLS-II/bluesky#1112] opened 2018-11-06 17:25 UTC
`RE(count([fccd], num=10))`  # or some num that will keep the detector busy for ~10s of seconds

Hit Ctrl^C

`RE.resume()`

Now force the data to be read, eliminating all our various modes of "laziness".

`h = db[-1]`

`import numpy`

`[numpy.array(row) for row in h.data('fccd_image')]`

If that last line raises an error similar to:

`ValueError: Index (2070) out of range (0-2068)`

Ignoring the specific numbers, of course, then we have reproduced the issue.

**Comment by cmazzoli** [comment] 2018-11-06 20:15
```
In [33]: RE(ct(dets,num=100))
Transient Scan ID: 111326     Time: 2018/11/06 14:59:09
Persistent Unique Scan ID: '19b0ec21-77f4-4f5f-a950-4cd61c97c518'
/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/ophyd/device.py:738: UserWarning: 'signal_names' has been renamed 'component_names' for clarity because it may include a mixture of Signals and Devices -- any Components. This alias may be removed in a future release of ophyd.
  warnings.warn("'signal_names' has been renamed 'component_names' for "
New stream: 'baseline'
New stream: 'primary'                                                                                                                                                         
+-----------+------------+-------------------+-------------------+
|   seq_num |       time | fccd_stats2_total | fccd_stats3_total |
+-----------+------------+-------------------+-------------------+
^C|         1 | 14:59:14.2 |             31970 |            328337 |
A 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.
Deferred pause acknowledged. Continuing to checkpoint.
|         2 | 14:59:14.7 |             33798 |            337078 |
Pausing...
---------------------------------------------------------------------------
RunEngineInterrupted                      Traceback (most recent call last)
~/Beamline/BDT/2018_11_05/energy_scan.py in <module>()
----> 1 RE(ct(dets,num=100))

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    671 
    672             if self._interrupted:
--> 673                 raise RunEngineInterrupted(self.pause_msg) from None
    674 
    675         return tuple(self._run_start_uids)

RunEngineInterrupted: 
Your RunEngine is entering a paused state. These are your options for changing
the state of the RunEngine:

RE.resume()    Resume the plan.
RE.abort()     Perform cleanup, then kill plan. Mark exit_stats='aborted'.
RE.stop()      Perform cleanup, then kill plan. Mark exit_status='success'.
RE.halt()      Emergency Stop: Do not perform cleanup --- just stop.


In [34]: RE.resume()
|         3 | 14:59:31.7 |             35190 |            350236 |
|         4 | 14:59:32.1 |             34378 |            328578 |
|         5 | 14:59:32.5 |             35652 |            322465 |
|         6 | 14:59:32.9 |             37422 |            346552 |
|         7 | 14:59:33.4 |             29894 |            304114 |
|         8 | 14:59:33.8 |             30440 |            322352 |                                                                                                            
|         9 | 14:59:34.2 |             33146 |            322301 |                                                                                                            
|        10 | 14:59:34.6 |             35954 |            332370 |
|        11 | 14:59:35.0 |             33328 |            336697 |                                                                                                            
|        12 | 14:59:35.4 |             33831 |            306573 |                                                                                                            
|        13 | 14:59:35.8 |             33489 |            319502 |                                                                                                            
|        14 | 14:59:36.2 |             35290 |            340940 |                                                                                                            
|        15 | 14:59:36.6 |             33943 |            329420 |
|        16 | 14:59:37.0 |             32138 |            320128 |                                                                                                            
|        17 | 14:59:37.4 |             35244 |            303431 |                                                                                                            
|        18 | 14:59:37.8 |             28598 |            301790 |
|        19 | 14:59:38.2 |             33139 |            309255 |
|        20 | 14:59:38.6 |             32839 |            315094 |                                                                                                            
|        21 | 14:59:39.0 |             28852 |            296118 |                                                                                                            
|        22 | 14:59:39.4 |             33682 |            328811 |                                                                                                            
|        23 | 14:59:39.8 |             31473 |            333137 |
/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/nslsii/__init__.py:262: UserWarning: This olog is giving errors. This will not be logged.Error:HTTPSConnectionPool(host='xf23id1-log.cs.nsls2.local', port=8181): Read timed out. (read timeout=30)
  'Error:' + str(exc))
|        24 | 14:59:40.2 |             31134 |            315968 |
|        25 | 14:59:40.6 |             28107 |            293783 |
|        26 | 14:59:41.0 |             32897 |            329220 |
|        27 | 14:59:41.4 |             30551 |            298500 |                                                                                                            
|        28 | 14:59:41.8 |             31621 |            313097 |
|        29 | 14:59:42.2 |             32094 |            308551 |                                                                                                            
|        30 | 14:59:42.6 |             34601 |            322165 |
|        31 | 14:59:43.0 |             31320 |            293500 |                                                                                                            
|        32 | 14:59:43.4 |             32993 |            316849 |
|        33 | 14:59:43.8 |             33548 |            317780 |                                                                                                            
|        34 | 14:59:44.2 |             30693 |            299659 |                                                                                                            
|        35 | 14:59:44.6 |             33532 |            326038 |
|        36 | 14:59:45.0 |             32598 |            308967 |                                                                                                            
|        37 | 14:59:45.4 |             30205 |            291408 |
|        38 | 14:59:45.8 |             32467 |            316811 |                                                                                                            
|        39 | 14:59:46.3 |             32160 |            302715 |                                                                                                            
|        40 | 14:59:46.7 |             32251 |            306665 |                                                                                                            
|        41 | 14:59:47.1 |             35883 |            338607 |                                                                                                            
|        42 | 14:59:47.5 |             31406 |            336291 |                                                                                                            
|        43 | 14:59:47.9 |             32697 |            314144 |                                                                                                            
|        44 | 14:59:48.4 |             32013 |            313725 |                                                                                                            
|        45 | 14:59:48.7 |             31179 |            318174 |
|        46 | 14:59:49.2 |             29239 |            294213 |                                                                                                            
|        47 | 14:59:49.6 |             33449 |            311829 |                                                                                                            
|        48 | 14:59:50.0 |             32064 |            318088 |                                                                                                            
|        49 | 14:59:50.4 |             29080 |            306126 |                                                                                                            
+-----------+------------+-------------------+-------------------+
|   seq_num |       time | fccd_stats2_total | fccd_stats3_total |
+-----------+------------+-------------------+-------------------+
|        50 | 14:59:50.8 |             30501 |            317142 |
|        51 | 14:59:51.2 |             31830 |            322793 |                                                                                                            
|        52 | 14:59:51.6 |             32618 |            316470 |
|        53 | 14:59:52.0 |             30138 |            308112 |
|        54 | 14:59:52.4 |             37354 |            341639 |
|        55 | 14:59:52.8 |             31304 |            303483 |
|        56 | 14:59:53.2 |             30176 |            298484 |                                                                                                            
|        57 | 14:59:53.6 |             33700 |            330788 |                                                                                                            
|        58 | 14:59:54.0 |             31159 |            315694 |                                                                                                            
|        59 | 14:59:54.4 |             30036 |            298488 |
|        60 | 14:59:54.8 |             27814 |            294222 |
|        61 | 14:59:55.2 |             30855 |            324930 |
|        62 | 14:59:55.6 |             31980 |            310809 |
|        63 | 14:59:56.0 |             33343 |            305786 |                                                                                                            
|        64 | 14:59:56.4 |             28245 |            293384 |
|        65 | 14:59:56.8 |             31716 |            313328 |
|        66 | 14:59:57.2 |             30213 |            307381 |
|        67 | 14:59:57.6 |             33513 |            327995 |                                                                                                            
|        68 | 14:59:58.0 |             32600 |            302484 |                                                                                                            
|        69 | 14:59:58.4 |             33407 |            318315 |
|        70 | 14:59:58.7 |             33623 |            309990 |
|        71 | 14:59:59.1 |             32566 |            300645 |
|        72 | 14:59:59.5 |             31971 |            295368 |
|        73 | 14:59:59.9 |             33173 |            318238 |                                                                                                            
|        74 | 15:00:00.3 |             28986 |            296834 |
|        75 | 15:00:00.8 |             33900 |            323705 |                                                                                                            
|        76 | 15:00:01.2 |             30966 |            306791 |                                                                                                            
|        77 | 15:00:01.6 |             25213 |            292219 |                                                                                                            
|        78 | 15:00:02.0 |             30803 |            299495 |                                                                                                            
|        79 | 15:00:02.4 |             30953 |            312538 |
|        80 | 15:00:02.8 |             32164 |            339406 |
|        81 | 15:00:03.2 |             31595 |            300375 |                                                                                                            
|        82 | 15:00:03.6 |             32605 |            316370 |                                                                                                            
|        83 | 15:00:04.0 |             30786 |            303174 |
|        84 | 15:00:04.4 |             26979 |            294933 |
|        85 | 15:00:04.8 |             31384 |            287143 |                                                                                                            
|        86 | 15:00:05.2 |             28062 |            295447 |
|        87 | 15:00:05.6 |             32313 |            320011 |                                                                                                            
|        88 | 15:00:06.0 |             32960 |            303864 |                                                                                                            
|        89 | 15:00:06.4 |             30833 |            303935 |
|        90 | 15:00:06.8 |             29902 |            321673 |
|        91 | 15:00:07.2 |             29139 |            299885 |                                                                                                            
|        92 | 15:00:07.6 |             32036 |            292232 |
|        93 | 15:00:08.0 |             29781 |            296167 |
|        94 | 15:00:08.4 |             25148 |            288358 |
|        95 | 15:00:08.8 |             30064 |            325114 |                                                                                                            
|        96 | 15:00:09.2 |             30777 |            321479 |
|        97 | 15:00:09.6 |             30334 |            289229 |                                                                                                            
|        98 | 15:00:10.0 |             33193 |            314040 |                                                                                                            
|        99 | 15:00:10.4 |             31444 |            307234 |                                                                                                            
+-----------+------------+-------------------+-------------------+
|   seq_num |       time | fccd_stats2_total | fccd_stats3_total |
+-----------+------------+-------------------+-------------------+
|       100 | 15:00:10.8 |             29809 |            306993 |
+-----------+------------+-------------------+-------------------+
generator count ['19b0ec21'] (scan num: 111326)
Out[34]: ['19b0ec21-77f4-4f5f-a950-4cd61c97c518']

In [39]: h=db[111326]

In [40]: import numpy

In [41]: [numpy.array(row) for row in h.data('fccd_image')]
    ...: 
    ...: 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/Beamline/BDT/2018_11_05/energy_scan.py in <module>()
----> 1 [numpy.array(row) for row in h.data('fccd_image')]
      2 

~/Beamline/BDT/2018_11_05/energy_scan.py in <listcomp>(.0)
----> 1 [numpy.array(row) for row in h.data('fccd_image')]
      2 

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/slicerator.py in <genexpr>(.0)
    224 
    225     def __iter__(self):
--> 226         return (self._get(i) for i in self.indices)
    227 
    228     def __len__(self):

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/slicerator.py in _get(self, key)
    204 
    205     def _get(self, key):
--> 206         return self._ancestor[key]
    207 
    208     def _map_index(self, key):

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/slicerator.py in __getitem__(self, i)
    185                 indices, new_length = key_to_indices(i, len(self))
    186                 if new_length is None:
--> 187                     return self._get(indices)
    188                 else:
    189                     return cls(self, indices, new_length, propagate_attrs)

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/pims/base_frames.py in __getitem__(self, key)
    150         """__getitem__ is handled by Slicerator. In all pims readers, the data
    151         returning function is get_frame."""
--> 152         return self.get_frame(key)
    153 
    154     def __iter__(self):

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/databroker/assets/handlers.py in get_frame(self, i)
    115 
    116     def get_frame(self, i):
--> 117         return Frame(self._dataset[self._start + i], frame_no=i)
    118 
    119     def __len__(self):

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/h5py/_hl/dataset.py in __getitem__(self, args)
    474 
    475         # Perform the dataspace selection.
--> 476         selection = sel.select(self.shape, args, dsid=self.id)
    477 
    478         if selection.nselect == 0:

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/h5py/_hl/selections.py in select(shape, args, dsid)
     92 
     93     sel = SimpleSelection(shape)
---> 94     sel[args]
     95     return sel
     96 

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/h5py/_hl/selections.py in __getitem__(self, args)
    259             return self
    260 
--> 261         start, count, step, scalar = _handle_simple(self.shape,args)
    262 
    263         self._id.select_hyperslab(start, count, step)

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/h5py/_hl/selections.py in _handle_simple(shape, args)
    449         else:
    450             try:
--> 451                 x,y,z = _translate_int(int(arg), length)
    452                 s = True
    453             except TypeError:

/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/h5py/_hl/selections.py in _translate_int(exp, length)
    469 
    470     if not 0<=exp<length:
--> 471         raise ValueError("Index (%s) out of range (0-%s)" % (exp, length-1))
    472 
    473     return exp, 1, 1

ValueError: Index (2) out of range (0-1)

In [42]: 
```

**Comment by cmazzoli** [comment] 2018-11-06 20:16
@danielballan - ran the test and we seem to see the error.  Stu

**Comment by danielballan** [comment] 2018-11-06 20:29
Having confirmed that we can reproduce this with _any_ pause, not specifically suspenders, I am confident that the issue is here:

https://github.com/NSLS-II-CSX/xf23id1_profiles/blob/master/profile_collection/startup/csx1/devices/areadetector.py#L143-L165

I think the best fix is to issue a new Resource document into the asset_cache on `resume()`. Will submit fix shortly.

**Comment by danielballan** [comment] 2018-11-06 20:49
This is a CSX-specific issue with regard to how the ophyd class interacts with the Fast CCD. I have submitted a proposed fix here: https://github.com/NSLS-II-CSX/xf23id1_profiles/pull/8

Let's continue testing and discussion on the PR. Closing as this is not a generic bluesky issue. Thanks again for performing the test.

**Closed by danielballan** 2018-11-06 20:49 UTC
Labels: task
