### ISSUE TITLE
TypeError exception raised during scan on timeout?

### ISSUE THREAD

**Issue by gjwillms** [NSLS-II/bluesky#637] opened 2017-01-30 13:04 UTC
Twice over the weekend, we have seen the following event end one of our scans.  A TypeError exception is raised on an apparent timeout on our scaler, which is also difficult to understand as an EPICS problem since I expect that VME-based IOC to be reliable.  I cannot reproduce the problem on demand.

It may be connected to long scans, as I have only seen it during these, but I have no evidence of this.
```pytb
|      1376 | 18:19:08.4 |  33.837500 |  25.469995 |    7060841 |  2083.7079 | 54987.7213 |   934.3435 |
/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/epics/ca.py:1248: UserWarning: ca.get('XF:05IDD-ES:1{Sclr:1}.S6') timed out after 1.00 seconds.
  warnings.warn(msg % (name(chid), timeout))
Still capturing data .... waiting.
Still capturing data .... waiting.
Still capturing data .... waiting.
Still capturing data .... giving up.
non-empty format string passed to object.__format__
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-52-6d187ef3cb42> in <module>()
----> 1 RE(hf2dxrf(xstart=33.6,xstepsize=0.0025,xnumstep=159,ystart=25.45,ystepsize=0.0025,ynumstep=79,acqtime=0.8,numrois=3,i0map_show=False,itmap_show=False,shutter=True,struck=True));RE(hf2dxrf(xstart=33.7,xstepsize=0.0005,xnumstep=79,ystart=25.56,ystepsize=0.0005,ynumstep=79,acqtime=0.8,numrois=3,i0map_show=False,itmap_show=False,shutter=True,struck=True));RE(hf2dxrf(xstart=33.805,xstepsize=0.0005,xnumstep=79,ystart=25.575,ystepsize=0.0005,ynumstep=79,acqtime=0.8,numrois=3,i0map_show=False,itmap_show=False,shutter=True,struck=True))

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/run_engine.py in __call__(self, plan, subs, raise_if_interrupted, **metadata_kw)
    596                     # it (unless it is a canceled error)
    597                     if exc is not None:
--> 598                         raise exc
    599 
    600             if raise_if_interrupted and self._interrupted:

/opt/conda_envs/collection-17Q1.0/lib/python3.5/asyncio/tasks.py in _step(***failed resolving arguments***)
    237                 # We use the `send` method directly, because coroutines
    238                 # don't have `__iter__` and `__next__` methods.
--> 239                 result = coro.send(None)
    240             else:
    241                 result = coro.throw(exc)

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/run_engine.py in _run(self)
   1002             self.log.error("Run aborted")
   1003             self.log.error("%r", err)
-> 1004             raise err
   1005         finally:
   1006             # Some done_callbacks may still be alive in other threads.

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/run_engine.py in _run(self)
    900                         resp = self._response_stack.pop()
    901                         try:
--> 902                             msg = self._plan_stack[-1].send(resp)
    903                         # We have exhausted the top generator
    904                         except StopIteration:

/home/xf05id1/ipython_ophyd/profile_xf05id1/startup/91-xrfsetup.py in hf2dxrf(xstart, xnumstep, xstepsize, ystart, ynumstep, ystepsize, shutter, acqtime, numrois, i0map_show, itmap_show, record_cryo, dpc, struck, setenergy, u_detune, echange_waittime)
    250     hf2dxrf_scanplan = OuterProductAbsScanPlan(det, hf_stage.y, ystart, ystop, ynumstep+1, hf_stage.x, xstart, xstop, xnumstep+1, True, md=md)
    251     hf2dxrf_scanplan = bp.subs_wrapper( hf2dxrf_scanplan, livecallbacks)
--> 252     scaninfo = yield from hf2dxrf_scanplan
    253 
    254     #TO-DO: implement fast shutter control (close)

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in subs_wrapper(plan, subs)
    928 
    929     return (yield from finalize_wrapper(_inner_plan(),
--> 930                                         _unsubscribe()))
    931 
    932 

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in finalize_wrapper(plan, final_plan, pause_for_debug)
   1023     cleanup = True
   1024     try:
-> 1025         ret = yield from plan
   1026     except GeneratorExit:
   1027         cleanup = False

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in _inner_plan()
    925     def _inner_plan():
    926         yield from _subscribe()
--> 927         return (yield from plan)
    928 
    929     return (yield from finalize_wrapper(_inner_plan(),

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in cls_plan()
   3108 
   3109                 for gen in plan_stack:
-> 3110                     yield from gen
   3111             finally:
   3112                 for key, val in current_settings.items():

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in fly_during_wrapper(plan, flyers)
   1381     plan1 = plan_mutator(plan, insert_after_open)
   1382     plan2 = plan_mutator(plan1, insert_before_close)
-> 1383     return (yield from plan2)
   1384 
   1385 

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in plan_mutator(plan, msg_proc)
    188                     continue
    189                 else:
--> 190                     raise ex
    191         # if inserting / mutating, put new generator on the stack
    192         # and replace the current msg with the first element from the

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in plan_mutator(plan, msg_proc)
    141             ret = result_stack.pop()
    142             try:
--> 143                 msg = plan_stack[-1].send(ret)
    144             except StopIteration as e:
    145                 # discard the exhausted generator

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in plan_mutator(plan, msg_proc)
    188                     continue
    189                 else:
--> 190                     raise ex
    191         # if inserting / mutating, put new generator on the stack
    192         # and replace the current msg with the first element from the

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in plan_mutator(plan, msg_proc)
    141             ret = result_stack.pop()
    142             try:
--> 143                 msg = plan_stack[-1].send(ret)
    144             except StopIteration as e:
    145                 # discard the exhausted generator

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in outer_product_scan(detectors, per_step, md, *args)
   2607 
   2608     return (yield from scan_nd(detectors, full_cycler,
-> 2609                                per_step=per_step, md=_md))
   2610 
   2611 

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in scan_nd(detectors, cycler, per_step, md)
   2499             yield from per_step(detectors, step, pos_cache)
   2500 
-> 2501     return (yield from inner_scan_nd())
   2502 
   2503 

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in dec_inner(*inner_args, **inner_kwargs)
     45                 plan = gen_func(*inner_args, **inner_kwargs)
     46                 plan = wrapper(plan, *args, **kwargs)
---> 47                 return (yield from plan)
     48             return dec_inner
     49         return dec

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in stage_wrapper(plan, devices)
   1508         return (yield from plan)
   1509 
-> 1510     return (yield from finalize_wrapper(inner(), unstage_devices()))
   1511 
   1512 

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in finalize_wrapper(plan, final_plan, pause_for_debug)
   1023     cleanup = True
   1024     try:
-> 1025         ret = yield from plan
   1026     except GeneratorExit:
   1027         cleanup = False

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in inner()
   1506     def inner():
   1507         yield from stage_devices()
-> 1508         return (yield from plan)
   1509 
   1510     return (yield from finalize_wrapper(inner(), unstage_devices()))

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in dec_inner(*inner_args, **inner_kwargs)
     45                 plan = gen_func(*inner_args, **inner_kwargs)
     46                 plan = wrapper(plan, *args, **kwargs)
---> 47                 return (yield from plan)
     48             return dec_inner
     49         return dec

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in run_wrapper(plan, md)
    871     """
    872     yield from open_run(md)
--> 873     yield from plan
    874     rs_uid = yield from close_run()
    875     return rs_uid

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in inner_scan_nd()
   2497     def inner_scan_nd():
   2498         for step in list(cycler):
-> 2499             yield from per_step(detectors, step, pos_cache)
   2500 
   2501     return (yield from inner_scan_nd())

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in one_nd_step(detectors, step, pos_cache)
   2454     motors = step.keys()
   2455     yield from move()
-> 2456     yield from trigger_and_read(list(detectors) + list(motors))
   2457 
   2458 

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in trigger_and_read(devices, name)
   1817             plan_stack.append(single_gen(Msg('read', obj)))
   1818 
-> 1819     return (yield from rewindable_wrapper(pchain(*plan_stack), rewindable))
   1820 
   1821 

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in rewindable_wrapper(plan, rewindable)
   1218         yield from set_rewindable(rewindable)
   1219         return (yield from finalize_wrapper(plan,
-> 1220                                             restore_rewindable()))
   1221     else:
   1222         return (yield from plan)

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in finalize_wrapper(plan, final_plan, pause_for_debug)
   1023     cleanup = True
   1024     try:
-> 1025         ret = yield from plan
   1026     except GeneratorExit:
   1027         cleanup = False

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in pchain(*args)
    286     rets = deque()
    287     for p in args:
--> 288         rets.append((yield from p))
    289     return tuple(rets)
    290 

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/utils.py in single_gen(msg)
    119         the input message
    120     '''
--> 121     return (yield msg)
    122 
    123 

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in plan_mutator(plan, msg_proc)
    213         try:
    214             # yield out the 'current message' and collect the return
--> 215             inner_ret = yield msg
    216         except GeneratorExit:
    217             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/plans.py in plan_mutator(plan, msg_proc)
    213         try:
    214             # yield out the 'current message' and collect the return
--> 215             inner_ret = yield msg
    216         except GeneratorExit:
    217             # special case GeneratorExit.  We must clean up all of our plans

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/run_engine.py in _run(self)
    951                         # exceptions (coming in via throw) can be
    952                         # raised
--> 953                         response = yield from coro(msg)
    954                     # special case `CancelledError` and let the outer
    955                     # exception block deal with it.

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/run_engine.py in _save(self, msg)
   1455                    time=ttime.time(), data=data, timestamps=timestamps,
   1456                    seq_num=seq_num, uid=event_uid)
-> 1457         yield from self.emit(DocumentNames.event, doc)
   1458         self.log.debug("Emitted Event with data keys %r (uid=%r)", data.keys(),
   1459                        event_uid)

/opt/conda_envs/collection-17Q1.0/lib/python3.5/asyncio/coroutines.py in coro(*args, **kw)
    204         @functools.wraps(func)
    205         def coro(*args, **kw):
--> 206             res = func(*args, **kw)
    207             if isinstance(res, futures.Future) or inspect.isgenerator(res):
    208                 res = yield from res

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/run_engine.py in emit(self, name, doc)
   1964         "Process blocking callbacks and schedule non-blocking callbacks."
   1965         jsonschema.validate(doc, schemas[name])
-> 1966         self.dispatcher.process(name, doc)
   1967 
   1968 

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/run_engine.py in process(self, name, doc)
   1976 
   1977     def process(self, name, doc):
-> 1978         exceptions = self.cb_registry.process(name, name.name, doc)
   1979         for exc, traceback in exceptions:
   1980             warn("A %r was raised during the processing of a %s "

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/utils.py in process(self, sig, *args, **kwargs)
    268             for cid, func in list(self.callbacks[sig].items()):
    269                 try:
--> 270                     func(*args, **kwargs)
    271                 except ReferenceError:
    272                     self._remove_proxy(func)

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/utils.py in __call__(self, *args, **kwargs)
    349             mtd = self.func
    350         # invoke the callable and return the result
--> 351         return mtd(*args, **kwargs)
    352 
    353     def __eq__(self, other):

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/callbacks/core.py in __call__(self, name, doc)
     19     def __call__(self, name, doc):
     20         "Dispatch to methods expecting particular doc types."
---> 21         return getattr(self, name)(doc)
     22 
     23     def event(self, doc):

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/callbacks/core.py in event(self, doc)
    600         cols = [f.format(**{k: data[k]})
    601                 if k in data else ' ' * self._format_info[k].width
--> 602                 for k, f in self._data_formats.items()]
    603         self._print('|' + '|'.join(cols) + '|')
    604         super().event(doc)

/opt/conda_envs/collection-17Q1.0/lib/python3.5/site-packages/bluesky/callbacks/core.py in <listcomp>(.0)
    600         cols = [f.format(**{k: data[k]})
    601                 if k in data else ' ' * self._format_info[k].width
--> 602                 for k, f in self._data_formats.items()]
    603         self._print('|' + '|'.join(cols) + '|')
    604         super().event(doc)

TypeError: non-empty format string passed to object.__format__
```

**Comment by tacaswell** [comment] 2017-01-31 16:41
Duplicate of https://github.com/NSLS-II/Bug-Reports/issues/155

**Closed by tacaswell** 2017-01-31 16:41 UTC
